/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 puf.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Puf(props) {
  const { color } = props.customColor
  const { color2 } = props.customColor2
  console.log(color2)
  const { nodes, materials } = useGLTF('/puf.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 27.89, 0]}>
        <group position={[0, 16.76, 0]}>
          <group position={[-10.91, -33.57, 0]}>
            <mesh geometry={nodes.legs.geometry} material={nodes.legs.material} position={[-10.91, -11.07, 0]}   material-color={color2}/>
            <mesh geometry={nodes.Cloner1.geometry} material={nodes.Cloner1.material} position={[10.91, 11.07, 0]}  material-color={color}/>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/puf.gltf')
