/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 puf2.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Puf2(props) {
  const { color } = props.customColor
  const { color2 } = props.customColor2
  const { nodes, materials } = useGLTF('/puf2.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0,0, 0]}>
      
        
            <group position={[-226.1, -12.68, -121.67]}>
              <mesh geometry={nodes.Cloner1.geometry} material={nodes.Cloner1.material} position={[237, 23.75, 121.67]} material-color={color} />
            </group>
            <mesh geometry={nodes.legs.geometry} material={nodes.legs.material} position={[-10.91, -11.07, 0]} material-color={color2} />
          </group>
        </group>
    
   
  )
}

useGLTF.preload('/puf2.gltf')
