/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group position={[-87.09, -199.03, 0]}>
          <mesh geometry={nodes.TV.geometry} material={nodes.TV.material} position={[-1.14, -6.67, 21.64]} rotation={[0, 0, Math.PI / 2]} />
          <mesh geometry={nodes.Würfel_1_2.geometry} material={nodes.Würfel_1_2.material} position={[-0.92, -3.38, 96.24]} />
          <mesh geometry={nodes.Würfel_2_2.geometry} material={nodes.Würfel_2_2.material} position={[-0.92, -3.38, 78.69]} />
          <mesh geometry={nodes.Würfel_2_3.geometry} material={nodes.Würfel_2_3.material} position={[-0.92, -3.38, -80.2]} />
          <mesh geometry={nodes.Würfel_3_3.geometry} material={nodes.Würfel_3_3.material} position={[-0.92, -3.38, -60.08]} />
          <mesh geometry={nodes.Würfel_5_4_3.geometry} material={nodes.Würfel_5_4_3.material} position={[-0.92, -3.38, -100.05]} />
          <mesh geometry={nodes.Zylinder_1.geometry} material={nodes.Zylinder_1.material} position={[67, 4.64, 97.3]} />
          <mesh geometry={nodes.Zylinder_2_2.geometry} material={nodes.Zylinder_2_2.material} position={[-68.68, 4.64, 97.3]} />
          <mesh geometry={nodes.Zylinder_3_2.geometry} material={nodes.Zylinder_3_2.material} position={[-68.68, -11.06, 97.3]} />
          <mesh geometry={nodes.Zylinder_4_2.geometry} material={nodes.Zylinder_4_2.material} position={[67, -11.01, 97.3]} />
        </group>
        <group position={[-100.17, -19.83, -50.12]}>
          <mesh geometry={nodes.Zylinder_3.geometry} material={nodes.Zylinder_3.material} position={[0, 0, -47.11]} />
          <mesh geometry={nodes.Kugel_7.geometry} material={nodes.Kugel_7.material} />
        </group>
        <group position={[-87.95, 116.79, -28.42]}>
          <mesh geometry={nodes.Zylinder_2.geometry} material={nodes.Zylinder_2.material} position={[0, 0, -47.11]} />
          <mesh geometry={nodes.Kugel_6.geometry} material={nodes.Kugel_6.material} />
        </group>
        <group position={[-45.2, 50.68, -14.05]}>
          <mesh geometry={nodes.Zylinder.geometry} material={nodes.Zylinder.material} position={[0, 0, -47.11]} />
          <mesh geometry={nodes.Kugel_5.geometry} material={nodes.Kugel_5.material} />
        </group>
        <mesh geometry={nodes.Zylinder_4.geometry} material={nodes.Zylinder_4.material} position={[-45.15, 50.66, -127.12]} />
        <mesh geometry={nodes.Zylinder_5.geometry} material={nodes.Zylinder_5.material} position={[-87.93, 116.76, -127.12]} />
        <mesh geometry={nodes.Zylinder_6.geometry} material={nodes.Zylinder_6.material} position={[-100.15, -19.9, -127.12]} />
        <group position={[-86.12, -202.22, 69.38]} rotation={[0, 1.57, 0]}>
          <mesh geometry={nodes.Kugel_3.geometry} material={nodes.Kugel_3.material} position={[0, 5.57, 30.79]} />
          <mesh geometry={nodes.Kugel_4.geometry} material={nodes.Kugel_4.material} position={[0, 5.57, -33.26]} />
          <mesh geometry={nodes.Würfel_4_5.geometry} material={nodes.Würfel_4_5.material} position={[0, 5.68, -0.52]} />
          <mesh geometry={nodes.Würfel_7_4.geometry} material={nodes.Würfel_7_4.material} position={[0, -0.44, -0.93]} />
        </group>
        <group position={[-176.16, -200.44, 0]}>
          <mesh geometry={nodes.Kugel_2.geometry} material={nodes.Kugel_2.material} position={[0, 4.01, 41.55]} />
          <mesh geometry={nodes.Würfel_3_2.geometry} material={nodes.Würfel_3_2.material} position={[0, -1.18, 70.22]} />
          <mesh geometry={nodes.Würfel_7_3.geometry} material={nodes.Würfel_7_3.material} position={[0, -2, 73.88]} />
        </group>
        <mesh geometry={nodes.Kugel.geometry} material={nodes.Kugel.material} position={[0, -196.43, 41.55]} />
        <mesh geometry={nodes.Würfel_2.geometry} material={nodes.Würfel_2.material} position={[0, -201.62, 70.22]} />
        <mesh geometry={nodes.Würfel_7_2.geometry} material={nodes.Würfel_7_2.material} position={[0, -202.44, 73.88]} />
        <group position={[-183.92, 52.18, 102.35]}>
          <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} />
          <mesh geometry={nodes.Cube_001.geometry} material={nodes.Cube_001.material} />
          <mesh geometry={nodes.Cube_002.geometry} material={nodes.Cube_002.material} />
        </group>
        <group position={[45.73, 52.18, 102.35]} rotation={[0, 0, Math.PI]}>
          <mesh geometry={nodes.Cube_001_2.geometry} material={nodes.Cube_001_2.material} />
          <mesh geometry={nodes.Cube_002_2.geometry} material={nodes.Cube_002_2.material} />
          <mesh geometry={nodes.Cube_2.geometry} material={nodes.Cube_2.material} />
        </group>
        <group position={[78.99, -70.2, 114.51]} rotation={[0, 0, -0.71]}>
          <mesh geometry={nodes.lamp_base_Boole2_antidamage_extr.geometry} material={nodes.lamp_base_Boole2_antidamage_extr.material} />
          <mesh geometry={nodes.lamp_base_Boole2_antidamage_extr_Cap_19.geometry} material={nodes.lamp_base_Boole2_antidamage_extr_Cap_19.material} />
          <mesh geometry={nodes.lamp_base_Boole2_antidamage_extr_Cap_22.geometry} material={nodes.lamp_base_Boole2_antidamage_extr_Cap_22.material} />
          <mesh geometry={nodes.lamp_base_Boole2_Cylinder21.geometry} material={nodes.lamp_base_Boole2_Cylinder21.material} />
          <mesh geometry={nodes.lamp_base_Boole2_Vyta_en_.geometry} material={nodes.lamp_base_Boole2_Vyta_en_.material} />
          <mesh geometry={nodes.lamp_base_Boole2_Vyta_en__Cap_17.geometry} material={nodes.lamp_base_Boole2_Vyta_en__Cap_17.material} />
          <mesh geometry={nodes.lamp_base_Boole2_Vyta_en__Cap_23.geometry} material={nodes.lamp_base_Boole2_Vyta_en__Cap_23.material} />
          <mesh geometry={nodes.lamp_base_Cylinder10.geometry} material={nodes.lamp_base_Cylinder10.material} />
          <mesh geometry={nodes.lamp_base_pitchforkdown_Krychle.geometry} material={nodes.lamp_base_pitchforkdown_Krychle.material} />
          <mesh geometry={nodes.lamp_base_pitchforkdown_Symetrie_Krychle_11_Krychle_1.geometry} material={nodes.lamp_base_pitchforkdown_Symetrie_Krychle_11_Krychle_1.material} />
          <mesh geometry={nodes.lamp_base_pitchforkdown_Symmetry1_screw.geometry} material={nodes.lamp_base_pitchforkdown_Symmetry1_screw.material} />
          <mesh geometry={nodes.lamp_base_pitchforkdown_Trubka.geometry} material={nodes.lamp_base_pitchforkdown_Trubka.material} />
          <mesh geometry={nodes.lamp_base_stickright_stickright1.geometry} material={nodes.lamp_base_stickright_stickright1.material} />
          <mesh geometry={nodes.lamp_base_Symmetry_1_mot_Extrude1.geometry} material={nodes.lamp_base_Symmetry_1_mot_Extrude1.material} />
          <mesh geometry={nodes.lamp_base_Symmetry_1_mot_Extrude1_Cap_15.geometry} material={nodes.lamp_base_Symmetry_1_mot_Extrude1_Cap_15.material} />
          <mesh geometry={nodes.lamp_base_Symmetry_1_mot_Extrude1_Cap_25.geometry} material={nodes.lamp_base_Symmetry_1_mot_Extrude1_Cap_25.material} />
          <mesh geometry={nodes.lamp_base_Symmetry_1_mot_Tube1.geometry} material={nodes.lamp_base_Symmetry_1_mot_Tube1.material} />
          <mesh geometry={nodes.lamp_base_Symmetry_1_mot_Tube_12.geometry} material={nodes.lamp_base_Symmetry_1_mot_Tube_12.material} />
          <mesh geometry={nodes.lamp_leglow_Boole3_Extrude3.geometry} material={nodes.lamp_leglow_Boole3_Extrude3.material} />
          <mesh geometry={nodes.lamp_leglow_Boole3_longstick_low.geometry} material={nodes.lamp_leglow_Boole3_longstick_low.material} />
          <mesh geometry={nodes.lamp_leglow_Cube1.geometry} material={nodes.lamp_leglow_Cube1.material} />
          <mesh geometry={nodes.lamp_leglow_Cylinder_1.geometry} material={nodes.lamp_leglow_Cylinder_1.material} />
          <mesh geometry={nodes.lamp_leglow_Cylinder_2.geometry} material={nodes.lamp_leglow_Cylinder_2.material} />
          <mesh geometry={nodes.lamp_leglow_longstickbase.geometry} material={nodes.lamp_leglow_longstickbase.material} />
          <mesh geometry={nodes.lamp_leglow_Tube3.geometry} material={nodes.lamp_leglow_Tube3.material} />
          <mesh geometry={nodes.lamp_legup_Boole1_Extrude.geometry} material={nodes.lamp_legup_Boole1_Extrude.material} />
          <mesh geometry={nodes.lamp_legup_Boole1_longstick_low1.geometry} material={nodes.lamp_legup_Boole1_longstick_low1.material} />
          <mesh geometry={nodes.lamp_legup_Boole_Extrude_3.geometry} material={nodes.lamp_legup_Boole_Extrude_3.material} />
          <mesh geometry={nodes.lamp_legup_Boole_glass.geometry} material={nodes.lamp_legup_Boole_glass.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cloner29_Capsule_010.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cloner29_Capsule_010.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cloner29_Capsule_125.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cloner29_Capsule_125.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cloner29_Capsule_225.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cloner29_Capsule_225.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cube2.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cube2.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cylinder12.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_02_Cylinder12.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cloner28_Capsule_014.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cloner28_Capsule_014.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cloner28_Capsule_128.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cloner28_Capsule_128.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cloner28_Capsule_214.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cloner28_Capsule_214.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cube.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cube.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cylinder3.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_12_Cylinder3.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cloner27_Capsule_020.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cloner27_Capsule_020.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cloner27_Capsule_129.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cloner27_Capsule_129.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cloner27_Capsule_27.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cloner27_Capsule_27.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cube3.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cube3.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cylinder29.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_23_Cylinder29.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cloner26_Capsule_023.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cloner26_Capsule_023.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cloner26_Capsule_126.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cloner26_Capsule_126.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cloner26_Capsule_2.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cloner26_Capsule_2.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cube5.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cube5.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cylinder31.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_33_Cylinder31.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cloner25_Capsule_024.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cloner25_Capsule_024.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cloner25_Capsule_123.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cloner25_Capsule_123.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cloner25_Capsule_25.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cloner25_Capsule_25.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cube6.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cube6.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cylinder20.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_44_Cylinder20.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cloner20_Capsule_021.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cloner20_Capsule_021.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cloner20_Capsule_121.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cloner20_Capsule_121.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cloner20_Capsule_213.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cloner20_Capsule_213.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cube10.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cube10.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cylinder26.geometry} material={nodes.lamp_legup_bulb_Cloner_1_0_bulb_5_Cylinder26.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cloner12_Capsule_08.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cloner12_Capsule_08.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cloner12_Capsule_16.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cloner12_Capsule_16.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cloner12_Capsule_224.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cloner12_Capsule_224.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cube18.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cube18.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cylinder1.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_04_Cylinder1.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cloner5_Capsule_03.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cloner5_Capsule_03.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cloner5_Capsule_117.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cloner5_Capsule_117.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cloner5_Capsule_22.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cloner5_Capsule_22.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cube25.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cube25.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cylinder18.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_1_Cylinder18.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cloner4_Capsule_02.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cloner4_Capsule_02.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cloner4_Capsule_124.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cloner4_Capsule_124.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cloner4_Capsule_220.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cloner4_Capsule_220.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cube31.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cube31.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cylinder23.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_24_Cylinder23.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cloner_Capsule_018.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cloner_Capsule_018.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cloner_Capsule_127.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cloner_Capsule_127.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cloner_Capsule_29.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cloner_Capsule_29.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cube30.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cube30.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cylinder8.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_32_Cylinder8.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cloner1_Capsule_026.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cloner1_Capsule_026.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cloner1_Capsule_116.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cloner1_Capsule_116.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cloner1_Capsule_210.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cloner1_Capsule_210.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cube29.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cube29.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cylinder6.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_4_Cylinder6.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cloner2_Capsule_011.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cloner2_Capsule_011.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cloner2_Capsule_111.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cloner2_Capsule_111.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cloner2_Capsule_228.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cloner2_Capsule_228.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cube28.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cube28.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cylinder33.geometry} material={nodes.lamp_legup_bulb_Cloner_1_1_bulb_52_Cylinder33.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cloner3_Capsule_0.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cloner3_Capsule_0.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cloner3_Capsule_1.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cloner3_Capsule_1.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cloner3_Capsule_215.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cloner3_Capsule_215.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cube27.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cube27.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cylinder15.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_01_Cylinder15.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cloner6_Capsule_01.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cloner6_Capsule_01.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cloner6_Capsule_11.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cloner6_Capsule_11.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cloner6_Capsule_218.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cloner6_Capsule_218.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cube26.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cube26.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cylinder22.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_14_Cylinder22.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cloner7_Capsule_04.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cloner7_Capsule_04.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cloner7_Capsule_12.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cloner7_Capsule_12.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cloner7_Capsule_219.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cloner7_Capsule_219.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cube24.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cube24.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cylinder19.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_21_Cylinder19.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cloner8_Capsule_05.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cloner8_Capsule_05.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cloner8_Capsule_14.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cloner8_Capsule_14.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cloner8_Capsule_223.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cloner8_Capsule_223.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cube23.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cube23.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cylinder16.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_34_Cylinder16.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cloner9_Capsule_06.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cloner9_Capsule_06.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cloner9_Capsule_15.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cloner9_Capsule_15.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cloner9_Capsule_227.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cloner9_Capsule_227.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cube22.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cube22.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cylinder13.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_41_Cylinder13.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cloner10_Capsule_07.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cloner10_Capsule_07.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cloner10_Capsule_18.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cloner10_Capsule_18.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cloner10_Capsule_229.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cloner10_Capsule_229.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cube21.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cube21.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cylinder11.geometry} material={nodes.lamp_legup_bulb_Cloner_1_2_bulb_53_Cylinder11.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cloner11_Capsule_09.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cloner11_Capsule_09.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cloner11_Capsule_19.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cloner11_Capsule_19.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cloner11_Capsule_226.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cloner11_Capsule_226.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cube20.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cube20.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cylinder7.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_0_Cylinder7.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cloner13_Capsule_012.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cloner13_Capsule_012.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cloner13_Capsule_113.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cloner13_Capsule_113.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cloner13_Capsule_222.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cloner13_Capsule_222.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cube19.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cube19.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cylinder5.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_13_Cylinder5.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cloner14_Capsule_013.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cloner14_Capsule_013.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cloner14_Capsule_114.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cloner14_Capsule_114.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cloner14_Capsule_221.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cloner14_Capsule_221.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cube17.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cube17.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cylinder2.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_2_Cylinder2.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cloner15_Capsule_015.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cloner15_Capsule_015.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cloner15_Capsule_118.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cloner15_Capsule_118.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cloner15_Capsule_217.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cloner15_Capsule_217.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cube16.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cube16.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cylinder.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_3_Cylinder.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cloner16_Capsule_016.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cloner16_Capsule_016.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cloner16_Capsule_120.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cloner16_Capsule_120.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cloner16_Capsule_216.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cloner16_Capsule_216.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cube15.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cube15.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cylinder30.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_43_Cylinder30.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cloner17_Capsule_017.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cloner17_Capsule_017.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cloner17_Capsule_122.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cloner17_Capsule_122.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cloner17_Capsule_212.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cloner17_Capsule_212.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cube14.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cube14.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cylinder34.geometry} material={nodes.lamp_legup_bulb_Cloner_1_3_bulb_51_Cylinder34.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cloner18_Capsule_019.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cloner18_Capsule_019.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cloner18_Capsule_119.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cloner18_Capsule_119.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cloner18_Capsule_28.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cloner18_Capsule_28.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cube13.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cube13.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cylinder28.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_03_Cylinder28.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cloner19_Capsule_022.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cloner19_Capsule_022.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cloner19_Capsule_115.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cloner19_Capsule_115.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cloner19_Capsule_26.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cloner19_Capsule_26.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cube12.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cube12.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cylinder27.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_11_Cylinder27.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cloner21_Capsule_028.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cloner21_Capsule_028.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cloner21_Capsule_112.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cloner21_Capsule_112.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cloner21_Capsule_23.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cloner21_Capsule_23.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cube11.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cube11.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cylinder25.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_22_Cylinder25.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cloner22_Capsule_025.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cloner22_Capsule_025.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cloner22_Capsule_110.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cloner22_Capsule_110.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cloner22_Capsule_21.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cloner22_Capsule_21.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cube9.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cube9.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cylinder32.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_31_Cylinder32.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cloner23_Capsule_029.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cloner23_Capsule_029.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cloner23_Capsule_17.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cloner23_Capsule_17.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cloner23_Capsule_24.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cloner23_Capsule_24.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cube8.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cube8.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cylinder4.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_42_Cylinder4.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cloner24_Capsule_027.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cloner24_Capsule_027.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cloner24_Capsule_13.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cloner24_Capsule_13.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cloner24_Capsule_211.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cloner24_Capsule_211.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cube7.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cube7.material} />
          <mesh geometry={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cylinder14.geometry} material={nodes.lamp_legup_bulb_Cloner_1_4_bulb_54_Cylinder14.material} />
          <mesh geometry={nodes.lamp_legup_clip.geometry} material={nodes.lamp_legup_clip.material} />
          <mesh geometry={nodes.lamp_legup_clip_Rounding_1.geometry} material={nodes.lamp_legup_clip_Rounding_1.material} />
          <mesh geometry={nodes.lamp_legup_clip_Rounding_1_Cap_14.geometry} material={nodes.lamp_legup_clip_Rounding_1_Cap_14.material} />
          <mesh geometry={nodes.lamp_legup_clip_Rounding_21.geometry} material={nodes.lamp_legup_clip_Rounding_21.material} />
          <mesh geometry={nodes.lamp_legup_clip_Rounding_21_Cap_26.geometry} material={nodes.lamp_legup_clip_Rounding_21_Cap_26.material} />
          <mesh geometry={nodes.lamp_legup_Cube4.geometry} material={nodes.lamp_legup_Cube4.material} />
          <mesh geometry={nodes.lamp_legup_Cylinder24.geometry} material={nodes.lamp_legup_Cylinder24.material} />
          <mesh geometry={nodes.lamp_legup_Cylinder_11.geometry} material={nodes.lamp_legup_Cylinder_11.material} />
          <mesh geometry={nodes.lamp_legup_Cylinder_3.geometry} material={nodes.lamp_legup_Cylinder_3.material} />
          <mesh geometry={nodes.lamp_legup_Extrude_1.geometry} material={nodes.lamp_legup_Extrude_1.material} />
          <mesh geometry={nodes.lamp_legup_Extrude_1_Rounding_11.geometry} material={nodes.lamp_legup_Extrude_1_Rounding_11.material} />
          <mesh geometry={nodes.lamp_legup_Extrude_1_Rounding_11_Cap_12.geometry} material={nodes.lamp_legup_Extrude_1_Rounding_11_Cap_12.material} />
          <mesh geometry={nodes.lamp_legup_Extrude_1_Rounding_2.geometry} material={nodes.lamp_legup_Extrude_1_Rounding_2.material} />
          <mesh geometry={nodes.lamp_legup_Extrude_1_Rounding_2_Cap_27.geometry} material={nodes.lamp_legup_Extrude_1_Rounding_2_Cap_27.material} />
          <mesh geometry={nodes.lamp_legup_glass1.geometry} material={nodes.lamp_legup_glass1.material} />
          <mesh geometry={nodes.lamp_legup_glass1_Cap_16.geometry} material={nodes.lamp_legup_glass1_Cap_16.material} />
          <mesh geometry={nodes.lamp_legup_glass1_Cap_2.geometry} material={nodes.lamp_legup_glass1_Cap_2.material} />
          <mesh geometry={nodes.lamp_legup_longstickbase1.geometry} material={nodes.lamp_legup_longstickbase1.material} />
          <mesh geometry={nodes.lamp_legup_mainswitch_Boole4_Extrude_2.geometry} material={nodes.lamp_legup_mainswitch_Boole4_Extrude_2.material} />
          <mesh geometry={nodes.lamp_legup_mainswitch_Boole4_switch_Extrude_31.geometry} material={nodes.lamp_legup_mainswitch_Boole4_switch_Extrude_31.material} />
          <mesh geometry={nodes.lamp_legup_mainswitch_Boole4_switch_Extrude_31_Cap_11.geometry} material={nodes.lamp_legup_mainswitch_Boole4_switch_Extrude_31_Cap_11.material} />
          <mesh geometry={nodes.lamp_legup_mainswitch_Boole4_switch_mainspace.geometry} material={nodes.lamp_legup_mainswitch_Boole4_switch_mainspace.material} />
          <mesh geometry={nodes.lamp_legup_mainswitch_clip1_Cylinder17.geometry} material={nodes.lamp_legup_mainswitch_clip1_Cylinder17.material} />
          <mesh geometry={nodes.lamp_legup_mainswitch_clip1_Extrude_21.geometry} material={nodes.lamp_legup_mainswitch_clip1_Extrude_21.material} />
          <mesh geometry={nodes.lamp_legup_mainswitch_clip1_Extrude_32.geometry} material={nodes.lamp_legup_mainswitch_clip1_Extrude_32.material} />
          <mesh geometry={nodes.lamp_legup_mainswitch_Cylinder9.geometry} material={nodes.lamp_legup_mainswitch_Cylinder9.material} />
          <mesh geometry={nodes.lamp_legup_Tube.geometry} material={nodes.lamp_legup_Tube.material} />
          <mesh geometry={nodes.lamp_pichforkup_fork_Cube_11_Cube_1.geometry} material={nodes.lamp_pichforkup_fork_Cube_11_Cube_1.material} />
          <mesh geometry={nodes.lamp_pichforkup_stick_stickright3_stickright2.geometry} material={nodes.lamp_pichforkup_stick_stickright3_stickright2.material} />
          <mesh geometry={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Extrude2.geometry} material={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Extrude2.material} />
          <mesh geometry={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Extrude2_Cap_1.geometry} material={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Extrude2_Cap_1.material} />
          <mesh geometry={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Extrude2_Cap_210.geometry} material={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Extrude2_Cap_210.material} />
          <mesh geometry={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Tube2.geometry} material={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Tube2.material} />
          <mesh geometry={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Tube_1.geometry} material={nodes.lamp_pichforkup_stick_Symmetry_11_mot1_Tube_1.material} />
          <mesh geometry={nodes.lamp_pichforkup_Symmetry_Tube_13.geometry} material={nodes.lamp_pichforkup_Symmetry_Tube_13.material} />
          <mesh geometry={nodes.lamp_pichforkup_tri.geometry} material={nodes.lamp_pichforkup_tri.material} />
          <mesh geometry={nodes.lamp_Tube_11.geometry} material={nodes.lamp_Tube_11.material} />
        </group>
        <group position={[-39.35, 48.76, 115.25]} rotation={[0, 0, -1.58]}>
          <mesh geometry={nodes.верх1_левый.geometry} material={nodes.верх1_левый.material} position={[-59.55, -63.12, -16.49]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.верх_правый.geometry} material={nodes.верх_правый.material} position={[25.9, -3.11, -16.49]} />
          <mesh geometry={nodes.держатель_стекла_1.geometry} material={nodes.держатель_стекла_1.material} position={[-10.14, -29.16, -26.26]} />
          <mesh geometry={nodes.низ_стола.geometry} material={nodes.низ_стола.material} position={[47.04, 43.73, -28.13]} />
          <mesh geometry={nodes.ножки.geometry} material={nodes.ножки.material} position={[-11.67, -27.72, -5.89]} />
          <mesh geometry={nodes.стекло.geometry} material={nodes.стекло.material} position={[-10.16, -29.01, -25.59]} />
        </group>
        <group position={[-246.26, 139.21, 40.19]}>
          <mesh geometry={nodes.Würfel_5_0.geometry} material={nodes.Würfel_5_0.material} />
          <mesh geometry={nodes.Würfel_5_1.geometry} material={nodes.Würfel_5_1.material} position={[0, 0, -5]} rotation={[0, -0.05, 0]} />
          <mesh geometry={nodes.Würfel_5_10.geometry} material={nodes.Würfel_5_10.material} position={[0, 0, -50]} rotation={[0, -0.47, 0]} />
          <mesh geometry={nodes.Würfel_5_11.geometry} material={nodes.Würfel_5_11.material} position={[0, 0, -55]} rotation={[0, -0.52, 0]} />
          <mesh geometry={nodes.Würfel_5_12.geometry} material={nodes.Würfel_5_12.material} position={[0, 0, -60]} rotation={[0, -0.56, 0]} />
          <mesh geometry={nodes.Würfel_5_13.geometry} material={nodes.Würfel_5_13.material} position={[0, 0, -65]} rotation={[0, -0.61, 0]} />
          <mesh geometry={nodes.Würfel_5_14.geometry} material={nodes.Würfel_5_14.material} position={[0, 0, -70]} rotation={[0, -0.66, 0]} />
          <mesh geometry={nodes.Würfel_5_15.geometry} material={nodes.Würfel_5_15.material} position={[0, 0, -75]} rotation={[0, -0.7, 0]} />
          <mesh geometry={nodes.Würfel_5_16.geometry} material={nodes.Würfel_5_16.material} position={[0, 0, -80]} rotation={[0, -0.75, 0]} />
          <mesh geometry={nodes.Würfel_5_17.geometry} material={nodes.Würfel_5_17.material} position={[0, 0, -85]} rotation={[0, -0.8, 0]} />
          <mesh geometry={nodes.Würfel_5_18.geometry} material={nodes.Würfel_5_18.material} position={[0, 0, -90]} rotation={[0, -0.85, 0]} />
          <mesh geometry={nodes.Würfel_5_19.geometry} material={nodes.Würfel_5_19.material} position={[0, 0, -95]} rotation={[0, -0.89, 0]} />
          <mesh geometry={nodes.Würfel_5_20.geometry} material={nodes.Würfel_5_20.material} position={[0, 0, -100]} rotation={[0, -0.94, 0]} />
          <mesh geometry={nodes.Würfel_5_21.geometry} material={nodes.Würfel_5_21.material} position={[0, 0, -105]} rotation={[0, -0.99, 0]} />
          <mesh geometry={nodes.Würfel_5_22.geometry} material={nodes.Würfel_5_22.material} position={[0, 0, -110]} rotation={[0, -1.03, 0]} />
          <mesh geometry={nodes.Würfel_5_23.geometry} material={nodes.Würfel_5_23.material} position={[0, 0, -115]} rotation={[0, -1.08, 0]} />
          <mesh geometry={nodes.Würfel_5_24.geometry} material={nodes.Würfel_5_24.material} position={[0, 0, -120]} rotation={[0, -1.13, 0]} />
          <mesh geometry={nodes.Würfel_5_25.geometry} material={nodes.Würfel_5_25.material} position={[0, 0, -125]} rotation={[0, -1.17, 0]} />
          <mesh geometry={nodes.Würfel_5_26.geometry} material={nodes.Würfel_5_26.material} position={[0, 0, -130]} rotation={[0, -1.22, 0]} />
          <mesh geometry={nodes.Würfel_5_2_2.geometry} material={nodes.Würfel_5_2_2.material} position={[0, 0, -10]} rotation={[0, -0.09, 0]} />
          <mesh geometry={nodes.Würfel_5_3_2.geometry} material={nodes.Würfel_5_3_2.material} position={[0, 0, -15]} rotation={[0, -0.14, 0]} />
          <mesh geometry={nodes.Würfel_5_4.geometry} material={nodes.Würfel_5_4.material} position={[0, 0, -20]} rotation={[0, -0.19, 0]} />
          <mesh geometry={nodes.Würfel_5_5.geometry} material={nodes.Würfel_5_5.material} position={[0, 0, -25]} rotation={[0, -0.23, 0]} />
          <mesh geometry={nodes.Würfel_5_6.geometry} material={nodes.Würfel_5_6.material} position={[0, 0, -30]} rotation={[0, -0.28, 0]} />
          <mesh geometry={nodes.Würfel_5_7.geometry} material={nodes.Würfel_5_7.material} position={[0, 0, -35]} rotation={[0, -0.33, 0]} />
          <mesh geometry={nodes.Würfel_5_8.geometry} material={nodes.Würfel_5_8.material} position={[0, 0, -40]} rotation={[0, -0.38, 0]} />
          <mesh geometry={nodes.Würfel_5_9.geometry} material={nodes.Würfel_5_9.material} position={[0, 0, -45]} rotation={[0, -0.42, 0]} />
        </group>
        <group position={[-246.26, -40.32, 40.19]}>
          <mesh geometry={nodes.Würfel_5_0_2.geometry} material={nodes.Würfel_5_0_2.material} />
          <mesh geometry={nodes.Würfel_5_10_2.geometry} material={nodes.Würfel_5_10_2.material} position={[0, 0, -50]} rotation={[0, -0.34, 0]} />
          <mesh geometry={nodes.Würfel_5_11_2.geometry} material={nodes.Würfel_5_11_2.material} position={[0, 0, -55]} rotation={[0, -0.37, 0]} />
          <mesh geometry={nodes.Würfel_5_12_2.geometry} material={nodes.Würfel_5_12_2.material} position={[0, 0, -60]} rotation={[0, -0.4, 0]} />
          <mesh geometry={nodes.Würfel_5_13_2.geometry} material={nodes.Würfel_5_13_2.material} position={[0, 0, -65]} rotation={[0, -0.44, 0]} />
          <mesh geometry={nodes.Würfel_5_14_2.geometry} material={nodes.Würfel_5_14_2.material} position={[0, 0, -70]} rotation={[0, -0.47, 0]} />
          <mesh geometry={nodes.Würfel_5_15_2.geometry} material={nodes.Würfel_5_15_2.material} position={[0, 0, -75]} rotation={[0, -0.5, 0]} />
          <mesh geometry={nodes.Würfel_5_16_2.geometry} material={nodes.Würfel_5_16_2.material} position={[0, 0, -80]} rotation={[0, -0.54, 0]} />
          <mesh geometry={nodes.Würfel_5_17_2.geometry} material={nodes.Würfel_5_17_2.material} position={[0, 0, -85]} rotation={[0, -0.57, 0]} />
          <mesh geometry={nodes.Würfel_5_18_2.geometry} material={nodes.Würfel_5_18_2.material} position={[0, 0, -90]} rotation={[0, -0.6, 0]} />
          <mesh geometry={nodes.Würfel_5_19_2.geometry} material={nodes.Würfel_5_19_2.material} position={[0, 0, -95]} rotation={[0, -0.64, 0]} />
          <mesh geometry={nodes.Würfel_5_1_2.geometry} material={nodes.Würfel_5_1_2.material} position={[0, 0, -5]} rotation={[0, -0.03, 0]} />
          <mesh geometry={nodes.Würfel_5_20_2.geometry} material={nodes.Würfel_5_20_2.material} position={[0, 0, -100]} rotation={[0, -0.67, 0]} />
          <mesh geometry={nodes.Würfel_5_21_2.geometry} material={nodes.Würfel_5_21_2.material} position={[0, 0, -105]} rotation={[0, -0.7, 0]} />
          <mesh geometry={nodes.Würfel_5_22_2.geometry} material={nodes.Würfel_5_22_2.material} position={[0, 0, -110]} rotation={[0, -0.74, 0]} />
          <mesh geometry={nodes.Würfel_5_23_2.geometry} material={nodes.Würfel_5_23_2.material} position={[0, 0, -115]} rotation={[0, -0.77, 0]} />
          <mesh geometry={nodes.Würfel_5_24_2.geometry} material={nodes.Würfel_5_24_2.material} position={[0, 0, -120]} rotation={[0, -0.81, 0]} />
          <mesh geometry={nodes.Würfel_5_25_2.geometry} material={nodes.Würfel_5_25_2.material} position={[0, 0, -125]} rotation={[0, -0.84, 0]} />
          <mesh geometry={nodes.Würfel_5_26_2.geometry} material={nodes.Würfel_5_26_2.material} position={[0, 0, -130]} rotation={[0, -0.87, 0]} />
          <mesh geometry={nodes.Würfel_5_2_3.geometry} material={nodes.Würfel_5_2_3.material} position={[0, 0, -10]} rotation={[0, -0.07, 0]} />
          <mesh geometry={nodes.Würfel_5_3_3.geometry} material={nodes.Würfel_5_3_3.material} position={[0, 0, -15]} rotation={[0, -0.1, 0]} />
          <mesh geometry={nodes.Würfel_5_4_2.geometry} material={nodes.Würfel_5_4_2.material} position={[0, 0, -20]} rotation={[0, -0.13, 0]} />
          <mesh geometry={nodes.Würfel_5_5_2.geometry} material={nodes.Würfel_5_5_2.material} position={[0, 0, -25]} rotation={[0, -0.17, 0]} />
          <mesh geometry={nodes.Würfel_5_6_2.geometry} material={nodes.Würfel_5_6_2.material} position={[0, 0, -30]} rotation={[0, -0.2, 0]} />
          <mesh geometry={nodes.Würfel_5_7_2.geometry} material={nodes.Würfel_5_7_2.material} position={[0, 0, -35]} rotation={[0, -0.23, 0]} />
          <mesh geometry={nodes.Würfel_5_8_2.geometry} material={nodes.Würfel_5_8_2.material} position={[0, 0, -40]} rotation={[0, -0.27, 0]} />
          <mesh geometry={nodes.Würfel_5_9_2.geometry} material={nodes.Würfel_5_9_2.material} position={[0, 0, -45]} rotation={[0, -0.3, 0]} />
        </group>
        <mesh geometry={nodes.Würfel_11_2.geometry} material={nodes.Würfel_11_2.material} position={[-246.83, -39.37, -95.82]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Würfel_6_3.geometry} material={nodes.Würfel_6_3.material} position={[-246.83, 139.49, -95.82]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Würfel_10.geometry} material={nodes.Würfel_10.material} position={[-257.42, 110.73, -85.27]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Würfel_11.geometry} material={nodes.Würfel_11.material} position={[-257.42, -70.32, -85.27]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Würfel_3.geometry} material={nodes.Würfel_3.material} position={[-257.42, 138.63, 0]} />
        <mesh geometry={nodes.Würfel_4.geometry} material={nodes.Würfel_4.material} position={[-257.42, -42.13, 0]} />
        <mesh geometry={nodes.Würfel_4_2.geometry} material={nodes.Würfel_4_2.material} position={[-257.42, 170.75, 36.01]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Würfel_4_3.geometry} material={nodes.Würfel_4_3.material} position={[-257.42, -98.44, 0]} />
        <mesh geometry={nodes.Würfel_5.geometry} material={nodes.Würfel_5.material} position={[-257.42, -8.85, -88.27]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Würfel_5_2.geometry} material={nodes.Würfel_5_2.material} position={[-257.42, 80.64, 0]} />
        <mesh geometry={nodes.Würfel_6.geometry} material={nodes.Würfel_6.material} position={[-257.42, 170.75, -87.84]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Würfel_6_2.geometry} material={nodes.Würfel_6_2.material} position={[-257.42, 199.71, 0]} />
        <mesh geometry={nodes.Würfel_7.geometry} material={nodes.Würfel_7.material} position={[-257.42, 21.18, 0]} />
        <mesh geometry={nodes.Würfel_8.geometry} material={nodes.Würfel_8.material} position={[-257.42, 110.73, 34.23]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Würfel_9.geometry} material={nodes.Würfel_9.material} position={[-257.42, -8.85, 36.01]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.Würfel_9_2.geometry} material={nodes.Würfel_9_2.material} position={[-257.42, -70.32, 34.23]} rotation={[Math.PI / 2, 0, 0]} />
        <group position={[0, 9.19, 0]}>
          <mesh geometry={nodes.Würfel_4_4.geometry} material={nodes.Würfel_4_4.material} position={[-267.25, -47.93, -25.67]} />
          <mesh geometry={nodes.Würfel_5_3.geometry} material={nodes.Würfel_5_3.material} position={[-267.25, 131.1, -25.67]} />
        </group>
      </group>
    </group> 
  )
}

useGLTF.preload('/scene.gltf') 
