/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 sofáDark.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SofaDark(props) {
  const group = useRef()

  const { nodes, materials } = useGLTF('/sofaDark.gltf')
  const { color } = props.customColor


  const handleClick = (() => {

    if (group.current) {
      console.log(group.current.children[0].name)
    
   
    }
  })


  return (
    <group ref={group} onClick={() => handleClick()} {...props} dispose={null}>

          <mesh name="coco"geometry={nodes.Cushion_Seats_002_Cushion_Seats.geometry} material={materials.Fabric_Couch} material-color={color} />
     
    
      <mesh geometry={nodes.Cushion_Seats_003_Cushion_Seats.geometry} material={materials.Fabric_Couch} />
      <mesh geometry={nodes.Cushion_Seats001_Cushion_Seats.geometry} material={materials.Fabric_Couch} />
      <mesh geometry={nodes.William_302_Zanotta_Legs001.geometry} material={materials.Metal} />
      <mesh geometry={nodes.William_302_Zanotta003.geometry} material={materials.Fabric_Couch} />
      <mesh geometry={nodes.William_302_Zanotta004.geometry} material={materials.Fabric_Couch} />
      <mesh geometry={nodes.William_302_Zanotta005.geometry} material={materials.Fabric_Couch} />
      <mesh geometry={nodes.William_Cushion_side.geometry} material={materials.Fabric_Couch} />
      <mesh geometry={nodes.William_Cushion_side001.geometry} material={materials.Fabric_Couch} position={[-0.02, -0.01, 0.01]} />
      <mesh geometry={nodes.William_Cushion003.geometry} material={materials.Fabric_Couch} />
      <mesh geometry={nodes.William_Cushion004.geometry} material={materials.Fabric_Couch} position={[0, 0.02, 0]} />
      <mesh geometry={nodes.William_Cushion005.geometry} material={materials.Fabric_Couch} />
    </group>
  )
}

useGLTF.preload('/sofaDark.gltf')
