/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 taburete.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Taburete(props) {
  const { nodes, materials } = useGLTF('/taburete.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/taburete.gltf')
