/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 textura.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Textura(props) {
  const { nodes, materials } = useGLTF('/textura.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh basicMaterial geometry={nodes.Cubo.geometry} material={materials.Mat} />
    </group>
  )
}

useGLTF.preload('/textura.gltf')
